apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-user
  namespace: gray
  labels:
    app: spring-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-user
  template:
    metadata:
      labels:
        app: spring-user
    spec:
      serviceAccountName: spring-cloud-k8s
      containers:
        - name: spring-user
          image: spring-user-gray:latest
          imagePullPolicy: Never
          command: ["java", "-jar","-Xms128m","-Xmx128m","app.jar"]
---
apiVersion: v1
kind: Service
metadata:
  name: spring-user
  namespace: gray
  labels:
    app: spring-user
spec:
  selector:
    app: spring-user
  ports:
    - port: 8080
      targetPort: 8080