apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-detail
  namespace: default
  labels:
    app: spring-detail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-detail
  template:
    metadata:
      labels:
        app: spring-detail
    spec:
      serviceAccountName: spring-cloud-k8s
      containers:
        - name: spring-detail
          image: spring-detail:latest
          imagePullPolicy: Never
          command: ["java", "-jar","-Xms128m","-Xmx128m","app.jar"]
---
apiVersion: v1
kind: Service
metadata:
  name: spring-detail
  namespace: default
  labels:
    app: spring-detail
spec:
  selector:
    app: spring-detail
  ports:
    - port: 8080
      targetPort: 8080